config/routes.rb
Rails.application.routes.draw do
  root to: 'over#index'
  get '/about-us', to: 'over#aboutus'
  get '/users', to: 'over#users'
  get '/search', to: 'over#search'
  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/over_controller.rb
class OverController < ApplicationController
    def index
        
        if params[:search]
            @posts = Post.where('title LIKE ?', "%#{params[:search]}%")
        else
            @@per_page = 2
            @page = params.fetch(:page,0).to_i
            @posts = Post.offset(@page * @@per_page).limit(@@per_page)
        end
    end
    def users
        @users = User.all
    end

    # def search
    #     params.require(:).permit(:search)
    # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:Title, :Tag, :Content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/over_helper.rb
module OverHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<%# <footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-12 mb-0 mb-md-4 pb-0 pb-md-2">
                <a href="#" class="logo-footer">
                    <img src="images/logo-light.png" height="24" alt="">
                </a>
                <p class="mt-4">Start working with Landrick that can provide everything you need to generate awareness, drive traffic, connect.</p>
                <ul class="list-unstyled social-icon foot-social-icon mb-0 mt-4">
                    <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="facebook" class="fea icon-sm fea-social"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="instagram" class="fea icon-sm fea-social"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="twitter" class="fea icon-sm fea-social"></i></a></li>
                    <li class="list-inline-item"><a href="javascript:void(0)" class="rounded"><i data-feather="linkedin" class="fea icon-sm fea-social"></i></a></li>
                </ul><!--end icon-->
            </div><!--end col-->
            
            <div class="col-lg-2 col-md-4 col-12 mt-4 mt-sm-0 pt-2 pt-sm-0">
                <h5 class="text-light footer-head">Company</h5>
                <ul class="list-unstyled footer-list mt-4">
                    <li><a href="page-aboutus.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> About us</a></li>
                    <li><a href="page-services.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Services</a></li>
                    <li><a href="page-team.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Team</a></li>
                    <li><a href="page-pricing.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Pricing</a></li>
                    <li><a href="page-portfolio-modern.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Project</a></li>
                    <li><a href="page-jobs.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Careers</a></li>
                    <li><a href="page-blog-grid.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Blog</a></li>
                    <li><a href="auth-cover-login.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Login</a></li>
                </ul>
            </div><!--end col-->
            
            <div class="col-lg-3 col-md-4 col-12 mt-4 mt-sm-0 pt-2 pt-sm-0">
                <h5 class="text-light footer-head">Usefull Links</h5>
                <ul class="list-unstyled footer-list mt-4">
                    <li><a href="page-terms.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Terms of Services</a></li>
                    <li><a href="page-privacy.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Privacy Policy</a></li>
                    <li><a href="documentation.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Documentation</a></li>
                    <li><a href="changelog.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Changelog</a></li>
                    <li><a href="components.html" class="text-foot"><i class="uil uil-angle-right-b me-1"></i> Components</a></li>
                </ul>
            </div><!--end col-->

            <div class="col-lg-3 col-md-4 col-12 mt-4 mt-sm-0 pt-2 pt-sm-0">
                <h5 class="text-light footer-head">Newsletter</h5>
                <p class="mt-4">Sign up and receive the latest tips via email.</p>
                <form>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="foot-subscribe mb-3">
                                <label class="form-label">Write your email <span class="text-danger">*</span></label>
                                <div class="form-icon position-relative">
                                    <i data-feather="mail" class="fea icon-sm icons"></i>
                                    <input type="email" name="email" id="emailsubscribe" class="form-control ps-5 rounded" placeholder="Your email : " required>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="d-grid">
                                <input type="submit" id="submitsubscribe" name="send" class="btn btn-soft-primary" value="Subscribe">
                            </div>
                        </div>
                    </div>
                </form>
            </div><!--end col-->
        </div><!--end row-->
    </div><!--end container-->
</footer> %>

<div class="position-relative mt-5">
    <div class="shape overflow-hidden text-footer">
        <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 48H1437.5H2880V0H2160C1442.5 52 720 0 720 0H0V48Z" fill="currentColor"></path>
        </svg>
    </div>
</div>
<footer class="footer footer-bar">
    <div class="container text-center">
        <div class="row align-items-center">
            <div class="col-sm-12">
                <div class="text-sm-center">
                    <p class="mb-0">© 2021 Blog VKU. Design with <i class="mdi mdi-heart text-danger"></i> by <a href="http://shreethemes.in/" target="_blank" class="text-reset">Phi Hùng</a>.</p>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<header id="topnav" class="defaultscroll sticky bg-light">
    <div class="container">
        <div class="logo">
            <%= link_to root_path do %>
                <%= image_tag "logo-dark.png", class: "logo-light-mode", height: "24"%>
                <%= image_tag "logo-light.png", class: "logo-dark-mode", height: "24"%>
            <% end %>
        </div>
        <ul class="buy-button list-inline mb-0">
            <li class="list-inline-item mb-0">
                <div class="dropdown">
                    <button type="button" class="btn btn-link text-decoration-none dropdown-toggle p-0 pe-2" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="bi bi-search"></i>
                    </button>
                    <div class="dropdown-menu dd-menu dropdown-menu-end bg-white shadow rounded border-0 mt-3 py-0" style="width: 300px;">
                        
                        <%= form_tag(root_path, method: :get) do %>
                            <%= text_field_tag :search, params[:term], class:"form-control border bg-white", placeholder:"Search..." %>
                        <% end %>
                    </div>
                </div>
            </li>
        </ul>
        <div class="menu-extras">
            <div class="menu-item">
                <a class="navbar-toggle" id="isToggle" onclick="toggleMenu()">
                    <div class="lines">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                </a>
            </div>
        </div>

        <div id="navigation">
            <ul class="navigation-menu nav-right">
                <li><%= link_to "Home", root_path, class: "sub-menu-item"%></li>
                <li><%= link_to "About Us", about_us_path, class: "sub-menu-item"%></li>
                <% if user_signed_in? %>
                    <li><%= link_to "Dashboard", posts_path, class: "nav-link"%></li>
                <% else %>
                    <li><%= link_to "LOGIN", new_user_session_path, class: "nav-link"%></li>
                 <% end %>
            </ul>
            <ul class="buy-menu-btn d-none">
                <li class="list-inline-item mb-0">
                    <div class="dropdown">
                        <button type="button" class="btn btn-link text-decoration-none dropdown-toggle p-0 pe-2" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="bi bi-search"></i>
                        </button>
                        <div class="dropdown-menu dd-menu dropdown-menu-end bg-white shadow rounded border-0 mt-3 py-0" style="width: 240px;">
                           <%= form_tag(root_path, method: :get) do %>
                                <%= text_field_tag :search, params[:term], class:"form-control border bg-white", placeholder:"Search..." %>
                            <% end %>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VKUBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap5.min.js"></script>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap5.min.css">
    <script>
      $(document).ready(function() {
          $('#tablesearch').DataTable();
      } );
    </script>
    <script src="https://cdn.tiny.cloud/1/y85pywkd046ctnwwsuxq5627d7kpn6y64j1vswrsn5s1w3qv/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>

  <%= render 'layouts/footer' %>
  <script>
    tinymce.init({
      selector: 'textarea', 
      plugin: 'a_tinymce_plugin',
      a_plugin_option: true,
      a_configuration_option: 400
    });

  </script>
  </body>
</html>

app/views/over/aboutus.html.erb
<section class="section bg-light">
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-12 text-center">
                <div class="section-title mb-4 pb-2">
                    <h4 class="title mb-4">We Are VKUer</h4>
                    <p class="text-muted para-desc mx-auto mb-0">All our dreams can come true, if we have the <span class="text-primary fw-bold">courage</span> to pursue them.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3 col-md-6 mt-4 pt-2">
                <div class="card team text-center bg-transparent border-0">
                    <div class="card-body p-0">
                        <div class="position-relative">
                            <%= image_tag "https://scontent-hkg4-2.xx.fbcdn.net/v/t1.18169-9/17190742_227587601041724_7153420415484182827_n.jpg?_nc_cat=111&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=gWThBOQ6veYAX9iHBAB&_nc_ht=scontent-hkg4-2.xx&oh=77ed4d61082ff5eeed2267c9f3a646b5&oe=60A01E73", class: "img-fluid avatar avatar-ex-large rounded-circle"%>
                        </div>
                        <div class="content pt-3 pb-3">
                            <h5 class="mb-0"><a href="javascript:void(0)" class="name text-dark">Tắt Đèn Tất Tố</a></h5>
                            <small class="designation text-muted">C.E.O</small>
                        </div>                                
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-4 pt-2">
                <div class="card team text-center bg-transparent border-0">
                    <div class="card-body p-0">
                        <div class="position-relative">
                            <%= image_tag "https://scontent-hkg4-1.xx.fbcdn.net/v/t1.6435-9/149258036_276927160693078_2687890634881571846_n.jpg?_nc_cat=102&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=uL2A1aiiZ8cAX-yEF8h&_nc_ht=scontent-hkg4-1.xx&oh=16d9d9e61ef40e274cf0b86a825a85bc&oe=609ED3DA", class: "img-fluid avatar avatar-ex-large rounded-circle"%>
                        </div>
                        <div class="content pt-3 pb-3">
                            <h5 class="mb-0"><a href="javascript:void(0)" class="name text-dark">Quốc Vinh</a></h5>
                            <small class="designation text-muted">Director</small>
                        </div>                                
                    </div>
                </div>
            </div><!--end col-->
            
            <div class="col-lg-3 col-md-6 mt-4 pt-2">
                <div class="card team text-center bg-transparent border-0">
                    <div class="card-body p-0">
                        <div class="position-relative">
                            <%= image_tag "https://scontent-hkg4-2.xx.fbcdn.net/v/t1.6435-9/123414539_1565630823639874_8413878845551310007_n.jpg?_nc_cat=109&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=Bx4u_9ezpjgAX__l4md&_nc_oc=AQmaibQUr3eNAtxhvw_jMXLCeaGSnqMBlaGMhR1i6F6sEz42XADH7u2dGwIIV0wiJVc&_nc_ht=scontent-hkg4-2.xx&oh=08b1105398f28ec0bc737b518a3cc0a4&oe=609DD1C9", class: "img-fluid avatar avatar-ex-large rounded-circle"%>
                        </div>
                        <div class="content pt-3 pb-3">
                            <h5 class="mb-0"><a href="javascript:void(0)" class="name text-dark">Huỳnh Nam Thành</a></h5>
                            <small class="designation text-muted">Manager</small>
                        </div>                                
                    </div>
                </div>
            </div><!--end col-->
            
            <div class="col-lg-3 col-md-6 mt-4 pt-2">
                <div class="card team text-center bg-transparent border-0">
                    <div class="card-body p-0">
                        <div class="position-relative">
                            <%= image_tag "https://scontent-hkg4-1.xx.fbcdn.net/v/t1.6435-9/83473752_2678166355757654_8632001896196889831_n.jpg?_nc_cat=103&ccb=1-3&_nc_sid=e3f864&_nc_ohc=S1C8ubrGCAQAX9xwwL2&_nc_ht=scontent-hkg4-1.xx&oh=d106b3906b1a9adabe3f0196f14023fe&oe=609D2E57", class: "img-fluid avatar avatar-ex-large rounded-circle"%>
                        </div>
                        <div class="content pt-3 pb-3">
                            <h5 class="mb-0"><a href="javascript:void(0)" class="name text-dark">Phii Hùng</a></h5>
                            <small class="designation text-muted">Developer</small>
                        </div>                                
                    </div>
                </div>
            </div><!--end col-->
        </div>
    </div>
</section>

app/views/over/users.html.erb
<section class="section mt-60">
  <div class="container mt-lg-3">
      <div class="row">
          <div class="col-lg-4 col-md-6 col-12 d-lg-block d-none">
              <div class="sidebar sticky-bar p-4 rounded bg-light">
                  
                  <div class="widget">
                      <ul class="list-unstyled sidebar-nav mb-0" id="navmenu-nav">
                          
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Posts', posts_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                            <%= link_to 'New Post', new_post_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Users', users_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Profile', edit_user_registration_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>

          <div class="col-lg-8 col-12">
              <div class="card border-0 rounded shadow">
                  <div class="card-body">
                      <h5 class="text-md-start text-center">Users: </h5>
                      <p id="notice"><%= notice %></p>
                      <table id="tablesearch" class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Email</th>
                            </tr>
                        </thead>
                        <tbody>
                        <% @users.each do |user| %>
                          <tr>
                            <td><%= user.id %></td>
                            <td><%= user.name %></td>
                            <td><%= user.email %></td>
                          </tr>
                        <% end %>
                        </tbody>
                    </table>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mt-2">
    <%= form.label :Title %>
    <%= form.text_field :Title, class:"form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :Tag %>
    <%= form.text_field :Tag, class:"form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :Content %>
    <%= form.text_area :Content, class:"form-control", rows:"20" %>
  </div>

  <div class="actions mt-3 mb-2">
    <%= form.submit "Post", class: "btn btn-primary btn-block"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<section class="section mt-60">
  <div class="container mt-lg-3">
      <div class="row">
          <div class="col-lg-4 col-md-6 col-12 d-lg-block d-none">
              <div class="sidebar sticky-bar p-4 rounded bg-light">
                  
                  <div class="widget">
                      <ul class="list-unstyled sidebar-nav mb-0" id="navmenu-nav">
                          
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Posts', posts_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                            <%= link_to 'New Post', new_post_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Users', users_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Profile', edit_user_registration_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>

          <div class="col-lg-8 col-12">
              <div class="card border-0 rounded shadow">
                  <div class="card-body">
                        <h5 class="text-md-start text-center">Posts: </h5>
                        <p id="notice"><%= notice %></p>
                        <%= render 'form', post: @post %>
                        <%= link_to 'Show', @post %> |
                        <%= link_to 'Back', posts_path %>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="section mt-60">
  <div class="container mt-lg-3">
      <div class="row">
          <div class="col-lg-4 col-md-6 col-12 d-lg-block d-none">
              <div class="sidebar sticky-bar p-4 rounded bg-light">
                  
                  <div class="widget">
                      <ul class="list-unstyled sidebar-nav mb-0" id="navmenu-nav">
                          
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Posts', posts_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                            <%= link_to 'New Post', new_post_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Users', users_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Profile', edit_user_registration_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>

          <div class="col-lg-8 col-12">
              <div class="card border-0 rounded shadow">
                  <div class="card-body">
                      <h5 class="text-md-start text-center">Posts: </h5>
                      <p id="notice"><%= notice %></p>
                      <table id="tablesearch" class="table table-striped">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th class="text-right">More</th>
                            </tr>
                        </thead>
                        <tbody>
                        <% @posts.each do |post| %>
                          <tr>
                            <td><%= post.id %></td>
                            <td><%= truncate(post.Title, length: 70) %></td>
                            <td class="text-right">
                              <%= link_to '', post ,class:"bi bi-eye"%>
                              <%= link_to '', edit_post_path(post),class:"bi bi-pen"%>
                              <%= link_to '', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"bi bi-trash" %>
                            </td>
                          </tr>
                        <% end %>
                        </tbody>
                    </table>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>

app/views/posts/new.html.erb
<section class="section mt-60">
  <div class="container mt-lg-3">
      <div class="row">
          <div class="col-lg-4 col-md-6 col-12 d-lg-block d-none">
              <div class="sidebar sticky-bar p-4 rounded bg-light">
                  
                  <div class="widget">
                      <ul class="list-unstyled sidebar-nav mb-0" id="navmenu-nav">
                          
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Posts', posts_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                            <%= link_to 'New Post', new_post_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Users', users_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Profile', edit_user_registration_path, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                          <li class="navbar-item account-menu px-0 mt-2">
                              <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:"navbar-link d-flex rounded shadow align-items-center py-3 px-4" %>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>

          <div class="col-lg-8 col-12">
              <div class="card border-0 rounded shadow">
                  <div class="card-body">
                      <h5 class="text-md-start text-center">Posts: </h5>
                      <p id="notice"><%= notice %></p>
                      <%= render 'form', post: @post %>
                      <%= link_to 'Back', posts_path %>
                  </div>
              </div>
          </div>
      </div>
  </div>
</section>

app/views/posts/show.html.erb
<%# <%= link_to 'Edit', edit_post_path(@post) %> |
<%# <%= link_to 'Back', posts_path %> 
<section class="bg-half">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8 col-md-10">
                <div class="section-title">
                    <div class="text-center">
                        <h1 class=" mb-5 pb-2 h1"><%= @post.Title %></h1>
                        <p id="notice"><%= notice %></p>
                    </div>
                    <p class="text-muted mb-0 mt-4"><%= simple_format(@post.Content)%></p>
                    <div class="tag text-sencondary mt-5">Tag: <%= @post.Tag %></div>
                </div>
            </div>
        </div>
    </div>
</section>